package require SnamlScript

output file AngularHello2.html

#__doctype html
_html "lang='en' ng-app"
  _head
    _title; quote "Live Data Binding of AngularJS by SnamlScript"; title_
    _script "src='https://ajax.googleapis.com/ajax/libs/angularjs/1.2.14/angular.min.js'"
    script_
  head_
  _body
    _label; quote "Name:"; label_
    _hr
    _input "type='text' ng-model='yourname' placeholder='Enter your name'"
    _hr
    quote "Hello - {{yourname}} - from Neatware."
    _hr
    quote "&copy;2014 Neatware. Generated by SnamlScript."
  body_
html_
