#
# 
#	This SnamlScript code was based on Mary Lou's (Manoela Ilic) beautiful code
#	 "Circular Content Carousel with jQuery". SnamlScript code generates HTML5 in index2.html
#	  
#
#
#
package require SnamlScript

output file index2.html

_html "lang='en'"
  _head
		#title
    _title; quote "Snaml Circular Carousel"; title_		

		# meta		
		_meta "charset='UTF-8'"
		_meta "http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'" 
		_meta "name='viewport' content='width=device-width, initial-scale=1.0'" 
    _meta "name='description' content='Circular Carousel with jQuery'"
    _meta "name='keywords' content='jquery, conent slider, carousel, circular, expanding, sliding, css3'"
		_meta "name='author' content='Neatware'"

		# link
		_link "rel='shortcut icon' href='../favicon.ico'" 
    _link "rel='stylesheet' type='text/css' href='css/demo.css'"
		_link "rel='stylesheet' type='text/css' href='css/style.css'"
		_link "rel='stylesheet' type='text/css' href='css/jquery.jscrollpane.css' media='all'"
		_link "href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow&v1' rel='stylesheet' type='text/css'"
		_link "href='http://fonts.googleapis.com/css?family=Coustard:900' rel='stylesheet' type='text/css'"
		_link "href='http://fonts.googleapis.com/css?family=Rochester' rel='stylesheet' type='text/css'"

		# script
		#//code.jquery.com/jquery-1.10.2.min.js
		#_script "type='text/javascript' src='http://code.jquery.com/jquery-1.10.1.min.js'"; script_

		_script "type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js'"; script_
		_script "type='text/javascript' src='js/jquery.easing.1.3.js'"; script_
		_script "type='text/javascript' src='js/jquery.mousewheel.js'"; script_
		_script "type='text/javascript' src='js/jquery.contentcarousel.js'"; script_  
	head_

  _body
		_div "class='container'"
			_h1; quote "Snaml Circular Carousel"; h1_

			_div "id='ca-container' class='ca-container'"
				_div "class='ca-wrapper'"

					set N 8
					for {set i 0} {$i < $N} {incr i} {
						_div "class='ca-item ca-item-[expr $i+1]'"
							_div "class='ca-item-main'"
								_div "class='ca-icon'";div_
								_h3; quote "Animal $i"; h3_
								_h4
									_span "class='ca-quote'"; quote "&ldquo;"; span_
									_span; quote "The greatness oits animals are treated."; span_
								h4_
								_a "href='#' class='ca-more'"; quote "more..."; a_
							div_
						
							_div "class='ca-content-wrapper'"
								_div "class='ca-content'"
									_h6; quote "Animals are not commodities"; h6_
									_a "href='#' class='ca-close'"; quote "close"; a_
									_div "class='ca-content-text'"
										_p; quote "I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, 
														that I neglect my talents. I should be incapable of drawing a single stroke at the present 
														moment; and yet I feel that I never was a greater artist than now."
										p_
									div_

									_ul
										_li; _a "href='#'"; quote "Read more"; a_; li_
										_li; _a "href='#'"; quote "Share this"; a_; li_
										_li; _a "href='#'"; quote "Become a member"; a_; li_
										_li; _a "href='#'"; quote "Donate"; a_; li_
									ul_
								div_
							div_
						div_
					}

				div_
			div_
			_h5; quote "Generated by SnamlScript"; h5_
		div_

		_script "type='text/javascript'"
			quote "\$('#ca-container').contentcarousel();"
		script_
  body_
html_